sudo: false

matrix:
  include:

    - name: "OpenJDK 8"
      language: java
      jdk: openjdk8
      os: linux
      script: ./gradlew

    - name: "OpenJDK 11"
      language: java
      jdk: openjdk11
      os: linux
      script: ./gradlew

    - env: COMPILER=g++-6
      language: cpp
      compiler: gcc
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - g++-6
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - env: COMPILER=g++-7
      language: cpp
      compiler: gcc
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - g++-7
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - env: COMPILER=g++-8
      language: cpp
      compiler: gcc
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - g++-8
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - env: COMPILER=clang++-4.0
      language: cpp
      compiler: clang
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - clang-4.0
            - libstdc++-6-dev
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
      script: ./cppbuild/cppbuild

    - env: COMPILER=clang++-5.0
      language: cpp
      compiler: clang
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
      script: ./cppbuild/cppbuild

    - env: COMPILER=clang++-6.0
      language: cpp
      compiler: clang
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - clang-6.0
            - libstdc++-7-dev
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
      script: ./cppbuild/cppbuild

    - env: COMPILER=clang++
      language: c++
      compiler: clang
      os: osx
      jdk: openjdk8
      script: ./cppbuild/cppbuild

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/